// Re-export from @know-yourself/core
export {
  DISCOVER_SELF_WELCOME_MESSAGE,
  REDUCE_INNER_FRICTION_WELCOME_MESSAGE,
  LIFE_CHOICE_WELCOME_MESSAGE,
  UNDERSTAND_OTHERS_WELCOME_MESSAGE,
  UNDERSTAND_CHILD_WELCOME_MESSAGE,
  UNDERSTAND_LOVER_WELCOME_MESSAGE,
  getWelcomeMessage,
} from '@know-yourself/core';
